[{
        milkshop_name: 臺北101觀景店,
        search_word: 迷客夏101,
        milk_lati: 25.033944484445076,
        milk_longi: 121.56476076913532,
        milkshop_link: https: //www.google.com.tw/maps/place/%E8%87%BA%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E4%BF%A1%E7%BE%A9%E8%B7%AF%E4%BA%94%E6%AE%B57%E8%99%9F89%E6%A8%93,
            milkshop_time: 10: 00– 21: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: -1,
        s_seven: -1,
        s_eight: -1,
        s_nine: -1,
        s_ten: -1,
        s_eleven: -1,
        s_twelve: -1,
        s_thirteen: -1,
        s_fourteen: -1,
        s_fifteen: -1,
        s_sixteen: -1,
        s_seventeen: -1,
        s_eighteen: -1,
        s_nineteen: -1,
        s_twenty: -1,
        s_twenty_one: -1,
        s_twenty_two: -1,
        s_twenty_three: -1
    },
    {
        milkshop_name: 臺北公館店,
        search_word: 迷客夏Milksha 臺北公館店,
        milk_lati: 25.015744343159703,
        milk_longi: 121.53227488747609,
        milkshop_link: https: //maps.app.goo.gl/ubc8ytbN3cGDRQi56,
            milkshop_time: 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 0,
        eleven: 9,
        twelve: 27,
        thirteen: 54,
        fourteen: 36,
        fifteen: 27,
        sixteen: 45,
        seventeen: 54,
        eighteen: 63,
        nineteen: 45,
        twenty: 18,
        twenty_one: 18,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 9,
        s_twelve: 27,
        s_thirteen: 9,
        s_fourteen: 9,
        s_fifteen: 0,
        s_sixteen: 0,
        s_seventeen: 9,
        s_eighteen: 18,
        s_nineteen: 36,
        s_twenty: 18,
        s_twenty_one: 9,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北龍山寺店,
        search_word: 迷客夏Milksha 萬華龍山寺店,
        milk_lati: 25.0354342,
        milk_longi: 121.4990228,
        milkshop_link: https: //goo.gl/maps/Hw247bhpaaxMSpz49,
            milkshop_time: 10: 00– 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 22,
        eleven: 33,
        twelve: 22,
        thirteen: 55,
        fourteen: 33,
        fifteen: 33,
        sixteen: 77,
        seventeen: 66,
        eighteen: 100,
        nineteen: 44,
        twenty: 22,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 11,
        s_eleven: 0,
        s_twelve: 22,
        s_thirteen: 44,
        s_fourteen: 100,
        s_fifteen: 66,
        s_sixteen: 55,
        s_seventeen: 22,
        s_eighteen: 33,
        s_nineteen: 44,
        s_twenty: 88,
        s_twenty_one: 44,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北忠孝復興店,
        search_word: 迷客夏 臺北忠孝復興店,
        milk_lati: 25.0427031,
        milk_longi: 121.5443302,
        milkshop_link: https: //goo.gl/maps/5yLdN6AWyDR5kAvm7?coh=178572&entry=tt,
            milkshop_time: 10: 00– 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 17,
        eleven: 21,
        twelve: 39,
        thirteen: 26,
        fourteen: 26,
        fifteen: 13,
        sixteen: 4,
        seventeen: 0,
        eighteen: 13,
        nineteen: 26,
        twenty: 60,
        twenty_one: 47,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 39,
        s_eleven: 8,
        s_twelve: 0,
        s_thirteen: 8,
        s_fourteen: 21,
        s_fifteen: 52,
        s_sixteen: 30,
        s_seventeen: 34,
        s_eighteen: 21,
        s_nineteen: 21,
        s_twenty: 21,
        s_twenty_one: 43,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北東區地下街店,
        search_word: 迷客夏Milksha 臺北東區地下街店,
        milk_lati: 25.0412903,
        milk_longi: 121.5516179,
        milkshop_link: https: //goo.gl/maps/NsT5SPkQfgoZiho39,
            milkshop_time: 11: 00 - 21: 30,
        milkshop_time_mor: 11,
        milkshop_time_nig: 21,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: -1,
        s_seven: -1,
        s_eight: -1,
        s_nine: -1,
        s_ten: -1,
        s_eleven: -1,
        s_twelve: -1,
        s_thirteen: -1,
        s_fourteen: -1,
        s_fifteen: -1,
        s_sixteen: -1,
        s_seventeen: -1,
        s_eighteen: -1,
        s_nineteen: -1,
        s_twenty: -1,
        s_twenty_one: -1,
        s_twenty_two: -1,
        s_twenty_three: -1
    },
    {
        milkshop_name: 臺北南港站前店,
        search_word: 迷客夏Milksha 臺北南港站前店,
        milk_lati: 25.0557946,
        milk_longi: 121.605967,
        milkshop_link: https: //goo.gl/maps/DGXMsNSxqNJTfmB56,
            milkshop_time: 平日10: 00 - 21: 00、 假日10: 00 - 20: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 14,
        eleven: 45,
        twelve: 80,
        thirteen: 100,
        fourteen: 80,
        fifteen: 68,
        sixteen: 48,
        seventeen: 57,
        eighteen: 51,
        nineteen: 40,
        twenty: 40,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 8,
        s_eleven: 17,
        s_twelve: 14,
        s_thirteen: 17,
        s_fourteen: 40,
        s_fifteen: 48,
        s_sixteen: 57,
        s_seventeen: 37,
        s_eighteen: 20,
        s_nineteen: 14,
        s_twenty: 0,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北和碩店,
        search_word: 迷客夏Milksha 臺北和碩店,
        milk_lati: 25.12717695,
        milk_longi: 121.47213185,
        milkshop_link: https: //goo.gl/maps/LajzCf96G6boMCSD8,
            milkshop_time: 平日： 09: 00 - 19: 30 假日： 休假,
        milkshop_time_mor: 9,
        milkshop_time_nig: 19,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: -1,
        s_seven: -1,
        s_eight: -1,
        s_nine: -1,
        s_ten: -1,
        s_eleven: -1,
        s_twelve: -1,
        s_thirteen: -1,
        s_fourteen: -1,
        s_fifteen: -1,
        s_sixteen: -1,
        s_seventeen: -1,
        s_eighteen: -1,
        s_nineteen: -1,
        s_twenty: -1,
        s_twenty_one: -1,
        s_twenty_two: -1,
        s_twenty_three: -1
    },
    {
        milkshop_name: 臺北通化店,
        search_word: 迷客夏Milksha 臺北通化店,
        milk_lati: 25.0319744,
        milk_longi: 121.5543649,
        milkshop_link: https: //maps.app.goo.gl/foqya9jAfUs28Z8LA,
            milkshop_time: 10: 00～ 22: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 6,
        eleven: 40,
        twelve: 60,
        thirteen: 93,
        fourteen: 93,
        fifteen: 73,
        sixteen: 93,
        seventeen: 46,
        eighteen: 20,
        nineteen: 6,
        twenty: 0,
        twenty_one: 6,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 46,
        s_twelve: 46,
        s_thirteen: 60,
        s_fourteen: 53,
        s_fifteen: 26,
        s_sixteen: 20,
        s_seventeen: 33,
        s_eighteen: 26,
        s_nineteen: 33,
        s_twenty: 13,
        s_twenty_one: 6,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北景美店,
        search_word: 迷客夏Milksha 臺北景美店,
        milk_lati: 24.9931303,
        milk_longi: 121.5414954,
        milkshop_link: https: //maps.app.goo.gl/uRdSY5Tu3ykRUyRw8,
            milkshop_time: 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 8,
        eleven: 8,
        twelve: 25,
        thirteen: 16,
        fourteen: 25,
        fifteen: 41,
        sixteen: 83,
        seventeen: 75,
        eighteen: 41,
        nineteen: 25,
        twenty: 16,
        twenty_one: 41,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 83,
        s_eleven: 75,
        s_twelve: 66,
        s_thirteen: 25,
        s_fourteen: 8,
        s_fifteen: 8,
        s_sixteen: 25,
        s_seventeen: 16,
        s_eighteen: 0,
        s_nineteen: 0,
        s_twenty: 16,
        s_twenty_one: 16,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北中山南西店,
        search_word: 迷客夏 臺北中山南西店,
        milk_lati: 25.0515173,
        milk_longi: 121.5215043,
        milkshop_link: https: //maps.app.goo.gl/fKRrdbsg9MAihDBX8,
            milkshop_time: 平日： 9: 00 - 22: 00 假日： 9: 00 - 22: 00,
        milkshop_time_mor: 9,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 8,
        ten: 25,
        eleven: 16,
        twelve: 25,
        thirteen: 25,
        fourteen: 8,
        fifteen: 8,
        sixteen: 8,
        seventeen: 25,
        eighteen: 16,
        nineteen: 0,
        twenty: 0,
        twenty_one: 8,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 66,
        s_ten: 33,
        s_eleven: 41,
        s_twelve: 50,
        s_thirteen: 50,
        s_fourteen: 33,
        s_fifteen: 25,
        s_sixteen: 41,
        s_seventeen: 16,
        s_eighteen: 8,
        s_nineteen: 0,
        s_twenty: 0,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北西門西寧店,
        search_word: 迷客夏Milksha 臺北西門西寧店,
        milk_lati: 25.044426,
        milk_longi: 121.506284,
        milkshop_link: https: //maps.app.goo.gl/R7U3FgzpJiFP1Mgb7,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 23,
        eleven: 7,
        twelve: 0,
        thirteen: 15,
        fourteen: 30,
        fifteen: 69,
        sixteen: 38,
        seventeen: 30,
        eighteen: 38,
        nineteen: 38,
        twenty: 15,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 7,
        s_eleven: 0,
        s_twelve: 0,
        s_thirteen: 0,
        s_fourteen: 7,
        s_fifteen: 23,
        s_sixteen: 7,
        s_seventeen: 0,
        s_eighteen: 0,
        s_nineteen: 0,
        s_twenty: 0,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北北醫莊敬店,
        search_word: 迷客夏 臺北北醫莊敬店,
        milk_lati: 25.0290906,
        milk_longi: 121.5624556,
        milkshop_link: https: //maps.app.goo.gl/yZUSzvYwHeL19yTu6,
            milkshop_time: 平日： 10: 00 - 21: 30 假日： 10: 00 - 21: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 18,
        eleven: 45,
        twelve: 45,
        thirteen: 27,
        fourteen: 36,
        fifteen: 45,
        sixteen: 27,
        seventeen: 9,
        eighteen: 0,
        nineteen: 0,
        twenty: 9,
        twenty_one: 27,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 45,
        s_eleven: 27,
        s_twelve: 36,
        s_thirteen: 45,
        s_fourteen: 36,
        s_fifteen: 54,
        s_sixteen: 45,
        s_seventeen: 45,
        s_eighteen: 9,
        s_nineteen: 9,
        s_twenty: 9,
        s_twenty_one: 18,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北興隆店,
        search_word: 迷客夏 臺北興隆店,
        milk_lati: 24.9989303,
        milk_longi: 121.556981,
        milkshop_link: https: //maps.app.goo.gl/HzHvwiriTua9DzRx6,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 0,
        eleven: 0,
        twelve: 4,
        thirteen: 12,
        fourteen: 12,
        fifteen: 24,
        sixteen: 20,
        seventeen: 24,
        eighteen: 48,
        nineteen: 68,
        twenty: 88,
        twenty_one: 64,
        twenty_two: 40,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 36,
        s_eleven: 80,
        s_twelve: 100,
        s_thirteen: 84,
        s_fourteen: 68,
        s_fifteen: 52,
        s_sixteen: 44,
        s_seventeen: 44,
        s_eighteen: 52,
        s_nineteen: 68,
        s_twenty: 72,
        s_twenty_one: 56,
        s_twenty_two: 28,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北永吉店,
        search_word: 迷客夏Milksha 臺北永吉店,
        milk_lati: 25.0432159,
        milk_longi: 121.5686969,
        milkshop_link: https: //www.google.com.tw/maps/place/11064%20%E5%8F%B0%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E6%B0%B8%E5%90%89%E8%B7%AF30%E5%B7%B7114%E8%99%9F,
            milkshop_time: 平日： 09: 00 - 22: 00 假日： 09: 00 - 22: 00,
        milkshop_time_mor: 9,
        milkshop_time_nig: 22,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: -1,
        s_seven: -1,
        s_eight: -1,
        s_nine: -1,
        s_ten: -1,
        s_eleven: -1,
        s_twelve: -1,
        s_thirteen: -1,
        s_fourteen: -1,
        s_fifteen: -1,
        s_sixteen: -1,
        s_seventeen: -1,
        s_eighteen: -1,
        s_nineteen: -1,
        s_twenty: -1,
        s_twenty_one: -1,
        s_twenty_two: -1,
        s_twenty_three: -1
    },
    {
        milkshop_name: 臺北遼寧店,
        search_word: 迷客夏Milksha 臺北遼寧店,
        milk_lati: 25.0486068,
        milk_longi: 121.5420395,
        milkshop_link: https: //maps.app.goo.gl/HSdP4MbMrSM1PLNJ7,
            milkshop_time: 平日： 09: 00 - 22: 00 假日： 09: 00 - 22: 00,
        milkshop_time_mor: 9,
        milkshop_time_nig: 22,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 4,
        s_ten: 9,
        s_eleven: 13,
        s_twelve: 18,
        s_thirteen: 31,
        s_fourteen: 31,
        s_fifteen: 50,
        s_sixteen: 45,
        s_seventeen: 40,
        s_eighteen: 54,
        s_nineteen: 68,
        s_twenty: 72,
        s_twenty_one: 45,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北虎林店,
        search_word: 迷客夏 臺北虎林店,
        milk_lati: 25.0400749,
        milk_longi: 121.576914,
        milkshop_link: https: //maps.app.goo.gl/E1V1BAKcsMp8j5P9A,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 13,
        s_twelve: 36,
        s_thirteen: 63,
        s_fourteen: 68,
        s_fifteen: 77,
        s_sixteen: 63,
        s_seventeen: 100,
        s_eighteen: 86,
        s_nineteen: 86,
        s_twenty: 59,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北伊通店,
        search_word: 迷客夏 臺北伊通店,
        milk_lati: 25.0528686,
        milk_longi: 121.5346997,
        milkshop_link: https: //maps.app.goo.gl/fS5JV3bWC6Pj1DH38,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 19,
        eleven: 39,
        twelve: 66,
        thirteen: 64,
        fourteen: 52,
        fifteen: 43,
        sixteen: 33,
        seventeen: 19,
        eighteen: 15,
        nineteen: 9,
        twenty: 7,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 33,
        s_twelve: 41,
        s_thirteen: 37,
        s_fourteen: 45,
        s_fifteen: 41,
        s_sixteen: 47,
        s_seventeen: 39,
        s_eighteen: 39,
        s_nineteen: 31,
        s_twenty: 25,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北天母店,
        search_word: 迷客夏 臺北天母店,
        milk_lati: 25.1073414,
        milk_longi: 121.5276157,
        milkshop_link: https: //maps.app.goo.gl/tVbTFPY65SmzjVja8,
            milkshop_time: 平日： 09: 00 - 22: 30 假日： 09: 00 - 22: 30,
        milkshop_time_mor: 9,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 33,
        ten: 50,
        eleven: 41,
        twelve: 16,
        thirteen: 16,
        fourteen: 33,
        fifteen: 75,
        sixteen: 100,
        seventeen: 83,
        eighteen: 33,
        nineteen: 16,
        twenty: 8,
        twenty_one: 33,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 16,
        s_ten: 41,
        s_eleven: 33,
        s_twelve: 41,
        s_thirteen: 25,
        s_fourteen: 16,
        s_fifteen: 16,
        s_sixteen: 41,
        s_seventeen: 41,
        s_eighteen: 41,
        s_nineteen: 41,
        s_twenty: 100,
        s_twenty_one: 83,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北南陽店,
        search_word: 迷客夏Milksha 臺北南陽店,
        milk_lati: 25.0442614,
        milk_longi: 121.5161377,
        milkshop_link: https: //maps.app.goo.gl/HqsPkfNJLCy6RLmH8,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 30 - 21: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 23,
        eleven: 56,
        twelve: 81,
        thirteen: 78,
        fourteen: 43,
        fifteen: 24,
        sixteen: 28,
        seventeen: 55,
        eighteen: 76,
        nineteen: 63,
        twenty: 0,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 47,
        s_twelve: 85,
        s_thirteen: 94,
        s_fourteen: 75,
        s_fifteen: 52,
        s_sixteen: 40,
        s_seventeen: 47,
        s_eighteen: 50,
        s_nineteen: 46,
        s_twenty: 0,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北北投店,
        search_word: 迷客夏 臺北北投店,
        milk_lati: 25.1330829,
        milk_longi: 121.5016116,
        milkshop_link: https: //maps.app.goo.gl/YVV7eYPTsubXNuFw5,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 40,
        eleven: 64,
        twelve: 70,
        thirteen: 68,
        fourteen: 54,
        fifteen: 58,
        sixteen: 72,
        seventeen: 80,
        eighteen: 82,
        nineteen: 72,
        twenty: 54,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 78,
        s_eleven: 86,
        s_twelve: 80,
        s_thirteen: 62,
        s_fourteen: 60,
        s_fifteen: 60,
        s_sixteen: 70,
        s_seventeen: 76,
        s_eighteen: 78,
        s_nineteen: 72,
        s_twenty: 54,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北錦州店,
        search_word: 迷客夏 臺北錦州店,
        milk_lati: 25.060538052410937,
        milk_longi: 121.54005747115103,
        milkshop_link: https: //maps.app.goo.gl/BqpuU4iQt39Z1oFn6,
            milkshop_time: 平日： 10: 30 - 21: 00 假日： 11: 00 - 21: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 25,
        eleven: 45,
        twelve: 78,
        thirteen: 80,
        fourteen: 84,
        fifteen: 76,
        sixteen: 72,
        seventeen: 62,
        eighteen: 58,
        nineteen: 47,
        twenty: 0,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 29,
        s_twelve: 43,
        s_thirteen: 58,
        s_fourteen: 72,
        s_fifteen: 88,
        s_sixteen: 94,
        s_seventeen: 80,
        s_eighteen: 56,
        s_nineteen: 0,
        s_twenty: 0,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北士林店,
        search_word: 迷客夏 臺北士林店,
        milk_lati: 25.13472317,
        milk_longi: 121.47355873,
        milkshop_link: https: //maps.app.goo.gl/BuHHZGJe6suTEJYHA,
            milkshop_time: 平日： 10: 00 - 22: 30 假日： 10: 00 - 22: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 66,
        eleven: 86,
        twelve: 80,
        thirteen: 46,
        fourteen: 46,
        fifteen: 26,
        sixteen: 20,
        seventeen: 20,
        eighteen: 40,
        nineteen: 20,
        twenty: 20,
        twenty_one: 26,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 40,
        s_eleven: 53,
        s_twelve: 60,
        s_thirteen: 33,
        s_fourteen: 13,
        s_fifteen: 13,
        s_sixteen: 26,
        s_seventeen: 60,
        s_eighteen: 66,
        s_nineteen: 73,
        s_twenty: 66,
        s_twenty_one: 46,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北瑞光店,
        search_word: 迷客夏Milksha 臺北瑞光店,
        milk_lati: 25.0687871,
        milk_longi: 121.5864989,
        milkshop_link: https: //www.google.com.tw/maps/place/11466%20%E5%8F%B0%E5%8C%97%E5%B8%82%E5%85%A7%E6%B9%96%E5%8D%80%E6%B0%91%E6%AC%8A%E6%9D%B1%E8%B7%AF%E5%85%AD%E6%AE%B5100%E8%99%9F,
            milkshop_time: 平日： 10: 00 - 21: 30 假日： 11: 00 - 21: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 4,
        eleven: 19,
        twelve: 47,
        thirteen: 42,
        fourteen: 19,
        fifteen: 4,
        sixteen: 0,
        seventeen: 14,
        eighteen: 42,
        nineteen: 61,
        twenty: 57,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 28,
        s_twelve: 23,
        s_thirteen: 28,
        s_fourteen: 66,
        s_fifteen: 80,
        s_sixteen: 100,
        s_seventeen: 85,
        s_eighteen: 85,
        s_nineteen: 80,
        s_twenty: 71,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北南昌店,
        search_word: 迷客夏 臺北南昌店,
        milk_lati: 25.0307524,
        milk_longi: 121.5177771,
        milkshop_link: https: //maps.app.goo.gl/A5k1zFoqVGH3SFTr6,
            milkshop_time: 平日： 10: 00 - 22: 30 假日： 10: 00 - 22: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 39,
        eleven: 58,
        twelve: 90,
        thirteen: 73,
        fourteen: 65,
        fifteen: 60,
        sixteen: 73,
        seventeen: 82,
        eighteen: 87,
        nineteen: 75,
        twenty: 60,
        twenty_one: 41,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 43,
        s_eleven: 53,
        s_twelve: 56,
        s_thirteen: 56,
        s_fourteen: 63,
        s_fifteen: 63,
        s_sixteen: 68,
        s_seventeen: 70,
        s_eighteen: 70,
        s_nineteen: 82,
        s_twenty: 68,
        s_twenty_one: 58,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北南京店,
        search_word: 迷客夏 臺北南京店,
        milk_lati: 25.0512094,
        milk_longi: 121.5609083,
        milkshop_link: https: //maps.app.goo.gl/zwt3d4KUtJizVEKB7,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 14,
        eleven: 42,
        twelve: 100,
        thirteen: 100,
        fourteen: 77,
        fifteen: 45,
        sixteen: 42,
        seventeen: 60,
        eighteen: 82,
        nineteen: 82,
        twenty: 77,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 20,
        s_twelve: 31,
        s_thirteen: 45,
        s_fourteen: 57,
        s_fifteen: 62,
        s_sixteen: 57,
        s_seventeen: 54,
        s_eighteen: 54,
        s_nineteen: 54,
        s_twenty: 37,
        s_twenty_one: 0,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北石牌店,
        search_word: 迷客夏 臺北石牌店,
        milk_lati: 25.1153283,
        milk_longi: 121.517775,
        milkshop_link: https: //maps.app.goo.gl/ajxDnqAWRaQThytF9,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 40,
        eleven: 50,
        twelve: 52,
        thirteen: 47,
        fourteen: 50,
        fifteen: 40,
        sixteen: 40,
        seventeen: 38,
        eighteen: 50,
        nineteen: 45,
        twenty: 30,
        twenty_one: 19,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 52,
        s_eleven: 69,
        s_twelve: 88,
        s_thirteen: 92,
        s_fourteen: 80,
        s_fifteen: 78,
        s_sixteen: 76,
        s_seventeen: 76,
        s_eighteen: 80,
        s_nineteen: 76,
        s_twenty: 61,
        s_twenty_one: 38,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北農安店,
        search_word: 迷客夏 MilkSha 臺北農安店,
        milk_lati: 25.0648566,
        milk_longi: 121.5237904,
        milkshop_link: https: //maps.app.goo.gl/skdNnvk8fBRoHyP37,
            milkshop_time: 平日： 10: 00 - 23: 00 假日： 10: 00 - 23: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 23,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 56,
        eleven: 100,
        twelve: 86,
        thirteen: 66,
        fourteen: 60,
        fifteen: 53,
        sixteen: 40,
        seventeen: 30,
        eighteen: 23,
        nineteen: 13,
        twenty: 13,
        twenty_one: 13,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 66,
        s_twelve: 80,
        s_thirteen: 66,
        s_fourteen: 63,
        s_fifteen: 56,
        s_sixteen: 60,
        s_seventeen: 63,
        s_eighteen: 56,
        s_nineteen: 40,
        s_twenty: 40,
        s_twenty_one: 30,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北圓山店,
        search_word: 迷客夏 臺北圓山店,
        milk_lati: 25.0721509,
        milk_longi: 121.5147971,
        milkshop_link: https: //maps.app.goo.gl/YhLC8fQQkkn1oJxWA,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 0,
        eleven: 0,
        twelve: 0,
        thirteen: 0,
        fourteen: 4,
        fifteen: 9,
        sixteen: 9,
        seventeen: 13,
        eighteen: 9,
        nineteen: 9,
        twenty: 4,
        twenty_one: 0,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 0,
        s_twelve: 4,
        s_thirteen: 13,
        s_fourteen: 36,
        s_fifteen: 40,
        s_sixteen: 36,
        s_seventeen: 50,
        s_eighteen: 100,
        s_nineteen: 95,
        s_twenty: 72,
        s_twenty_one: 27,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北延吉店,
        search_word: 迷客夏 臺北延吉店,
        milk_lati: 25.0387684,
        milk_longi: 121.555251,
        milkshop_link: https: //maps.app.goo.gl/3GRWNDhkpcQjUMYH6,
            milkshop_time: 平日： 09: 30 - 22: 30 假日： 10: 00 - 22: 30,
        milkshop_time_mor: 9,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 30,
        ten: 43,
        eleven: 43,
        twelve: 56,
        thirteen: 53,
        fourteen: 56,
        fifteen: 48,
        sixteen: 56,
        seventeen: 79,
        eighteen: 97,
        nineteen: 89,
        twenty: 82,
        twenty_one: 48,
        twenty_two: 17,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 12,
        s_eleven: 23,
        s_twelve: 30,
        s_thirteen: 30,
        s_fourteen: 41,
        s_fifteen: 51,
        s_sixteen: 61,
        s_seventeen: 66,
        s_eighteen: 48,
        s_nineteen: 33,
        s_twenty: 30,
        s_twenty_one: 20,
        s_twenty_two: 20,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北西門町店,
        search_word: 迷客夏 臺北西門町店,
        milk_lati: 25.0419573,
        milk_longi: 121.5072297,
        milkshop_link: https: //maps.app.goo.gl/y5yjJapEE6ZMKnxE9,
            milkshop_time: 平日： 10: 00 - 22: 30 假日： 10: 00 - 22: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 7,
        eleven: 13,
        twelve: 23,
        thirteen: 23,
        fourteen: 26,
        fifteen: 30,
        sixteen: 46,
        seventeen: 59,
        eighteen: 69,
        nineteen: 63,
        twenty: 63,
        twenty_one: 38,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 15,
        s_eleven: 32,
        s_twelve: 53,
        s_thirteen: 75,
        s_fourteen: 82,
        s_fifteen: 92,
        s_sixteen: 100,
        s_seventeen: 100,
        s_eighteen: 84,
        s_nineteen: 71,
        s_twenty: 61,
        s_twenty_one: 38,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北西湖店,
        search_word: 迷客夏Milksha 臺北西湖店,
        milk_lati: 25.0845978,
        milk_longi: 121.5674589,
        milkshop_link: https: //maps.app.goo.gl/8GA3rXCpeRAiziPW6,
            milkshop_time: 平日： 10: 00 - 21: 30 假日： 10: 00 - 21: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 21,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 70,
        eleven: 41,
        twelve: 41,
        thirteen: 29,
        fourteen: 29,
        fifteen: 41,
        sixteen: 47,
        seventeen: 35,
        eighteen: 41,
        nineteen: 58,
        twenty: 35,
        twenty_one: 35,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 29,
        s_eleven: 47,
        s_twelve: 47,
        s_thirteen: 58,
        s_fourteen: 64,
        s_fifteen: 70,
        s_sixteen: 70,
        s_seventeen: 58,
        s_eighteen: 35,
        s_nineteen: 23,
        s_twenty: 11,
        s_twenty_one: 11,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北車站店(櫃位門市),
        search_word: 迷客夏Milksha 臺北車站店,
        milk_lati: 25.046582,
        milk_longi: 121.5163683,
        milkshop_link: https: //maps.app.goo.gl/AKRXbEMstoLpuos4A,
            milkshop_time: 平日： 10: 00 - 22: 30 假日： 10: 00 - 22: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 11,
        eleven: 14,
        twelve: 29,
        thirteen: 26,
        fourteen: 38,
        fifteen: 73,
        sixteen: 76,
        seventeen: 91,
        eighteen: 76,
        nineteen: 64,
        twenty: 29,
        twenty_one: 14,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 35,
        s_eleven: 26,
        s_twelve: 32,
        s_thirteen: 20,
        s_fourteen: 8,
        s_fifteen: 11,
        s_sixteen: 17,
        s_seventeen: 35,
        s_eighteen: 44,
        s_nineteen: 44,
        s_twenty: 61,
        s_twenty_one: 58,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北政大店,
        search_word: 迷客夏Milksha 臺北政大店,
        milk_lati: 24.9879789,
        milk_longi: 121.5746215,
        milkshop_link: https: //maps.app.goo.gl/eHeo3sEMfwvvJxoa7,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 0,
        eleven: 11,
        twelve: 35,
        thirteen: 47,
        fourteen: 52,
        fifteen: 41,
        sixteen: 11,
        seventeen: 0,
        eighteen: 11,
        nineteen: 35,
        twenty: 47,
        twenty_one: 52,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 5,
        s_twelve: 11,
        s_thirteen: 29,
        s_fourteen: 23,
        s_fifteen: 17,
        s_sixteen: 17,
        s_seventeen: 29,
        s_eighteen: 41,
        s_nineteen: 41,
        s_twenty: 29,
        s_twenty_one: 29,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北昆陽店,
        search_word: 迷客夏Milksha 臺北昆陽店,
        milk_lati: 25.0500126,
        milk_longi: 121.5930925,
        milkshop_link: https: //maps.app.goo.gl/GDuvhwfMWy7f4cjg9,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 38,
        eleven: 46,
        twelve: 30,
        thirteen: 23,
        fourteen: 15,
        fifteen: 30,
        sixteen: 30,
        seventeen: 46,
        eighteen: 23,
        nineteen: 7,
        twenty: 7,
        twenty_one: 7,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 30,
        s_eleven: 23,
        s_twelve: 38,
        s_thirteen: 30,
        s_fourteen: 15,
        s_fifteen: 15,
        s_sixteen: 38,
        s_seventeen: 76,
        s_eighteen: 76,
        s_nineteen: 69,
        s_twenty: 76,
        s_twenty_one: 46,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北師大店,
        search_word: 迷客夏臺北師大店,
        milk_lati: 25.0243684,
        milk_longi: 121.5286511,
        milkshop_link: https: //maps.app.goo.gl/mEZyBqCtK8tpR4VX9,
            milkshop_time: 平日： 10: 00 - 22: 30 假日： 10: 00 - 23: 30,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 21,
        eleven: 50,
        twelve: 78,
        thirteen: 64,
        fourteen: 53,
        fifteen: 42,
        sixteen: 42,
        seventeen: 60,
        eighteen: 71,
        nineteen: 53,
        twenty: 39,
        twenty_one: 17,
        twenty_two: 17,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 39,
        s_eleven: 53,
        s_twelve: 57,
        s_thirteen: 50,
        s_fourteen: 39,
        s_fifteen: 57,
        s_sixteen: 71,
        s_seventeen: 100,
        s_eighteen: 96,
        s_nineteen: 78,
        s_twenty: 67,
        s_twenty_one: 57,
        s_twenty_two: 35,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北大直店,
        search_word: 迷客夏Milksha 臺北大直店,
        milk_lati: 25.0814509,
        milk_longi: 121.5488014,
        milkshop_link: https: //maps.app.goo.gl/PcHQeB6UPJmd61av5,
            milkshop_time: 平日： 10: 00 - 22: 00 假日： 10: 00 - 22: 00,
        milkshop_time_mor: 10,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 27,
        eleven: 40,
        twelve: 38,
        thirteen: 30,
        fourteen: 34,
        fifteen: 43,
        sixteen: 47,
        seventeen: 41,
        eighteen: 36,
        nineteen: 29,
        twenty: 18,
        twenty_one: 7,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 41,
        s_eleven: 61,
        s_twelve: 72,
        s_thirteen: 74,
        s_fourteen: 74,
        s_fifteen: 76,
        s_sixteen: 83,
        s_seventeen: 87,
        s_eighteen: 74,
        s_nineteen: 67,
        s_twenty: 50,
        s_twenty_one: 32,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name: 臺北華碩店(櫃位門市),
        search_word: 迷客夏Milksha 臺北華碩店,
        milk_lati: 25.1270049,
        milk_longi: 121.4708568,
        milkshop_link: https: //maps.app.goo.gl/75LtjMLJSNPQov4N7,
            milkshop_time: 平日： 08: 00 - 20: 30 假日： 休假,
        milkshop_time_mor: 8,
        milkshop_time_nig: 20,
        six: -1,
        seven: -1,
        eight: -1,
        nine: -1,
        ten: -1,
        eleven: -1,
        twelve: -1,
        thirteen: -1,
        fourteen: -1,
        fifteen: -1,
        sixteen: -1,
        seventeen: -1,
        eighteen: -1,
        nineteen: -1,
        twenty: -1,
        twenty_one: -1,
        twenty_two: -1,
        twenty_three: -1,
        s_six: -1,
        s_seven: -1,
        s_eight: -1,
        s_nine: -1,
        s_ten: -1,
        s_eleven: -1,
        s_twelve: -1,
        s_thirteen: -1,
        s_fourteen: -1,
        s_fifteen: -1,
        s_sixteen: -1,
        s_seventeen: -1,
        s_eighteen: -1,
        s_nineteen: -1,
        s_twenty: -1,
        s_twenty_one: -1,
        s_twenty_two: -1,
        s_twenty_three: -1
    },
    {
        milkshop_name: 臺北時代百貨店(櫃位門市),
        search_word: 迷客夏 臺北時代百貨店,
        milk_lati: 25.0406227,
        milk_longi: 121.5654586,
        milkshop_link: https: //maps.app.goo.gl/wW4ChDGBntodKNdK8,
            milkshop_time: 平日： 11: 00 - 22: 00 假日： 11: 00 - 22: 00,
        milkshop_time_mor: 11,
        milkshop_time_nig: 22,
        six: 0,
        seven: 0,
        eight: 0,
        nine: 0,
        ten: 0,
        eleven: 60,
        twelve: 32,
        thirteen: 20,
        fourteen: 36,
        fifteen: 28,
        sixteen: 32,
        seventeen: 16,
        eighteen: 12,
        nineteen: 4,
        twenty: 0,
        twenty_one: 12,
        twenty_two: 0,
        twenty_three: 0,
        s_six: 0,
        s_seven: 0,
        s_eight: 0,
        s_nine: 0,
        s_ten: 0,
        s_eleven: 48,
        s_twelve: 28,
        s_thirteen: 24,
        s_fourteen: 24,
        s_fifteen: 28,
        s_sixteen: 20,
        s_seventeen: 20,
        s_eighteen: 8,
        s_nineteen: 4,
        s_twenty: 8,
        s_twenty_one: 8,
        s_twenty_two: 0,
        s_twenty_three: 0
    },
    {
        milkshop_name:
    }
]